version: '3.8'

services:
  nest-app:
    image: meodel/nest-app:latest
    container_name: nest-app
    restart: always
    network_mode: host
    environment:
      - NODE_ENV=production
    ports:
      - "9036:9036"

networks:
  app-network:
    driver: bridge 