version: '3.8'

services:
  nest-app:
    image: meodel/nest-app:latest
    container_name: nest-app
    restart: always
    ports:
      - "9036:9036"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 