name: NestJS Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Docker Build and Push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build -t meodel/nest-app:latest .
        docker push meodel/nest-app:latest

    - name: Deploy to VPS
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: 45.81.84.133
        username: adminlocal
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 9036
        script: |
          docker pull meodel/nest-app:latest
          docker stop nest-app || true
          docker rm nest-app || true
          docker run -d --name nest-app --network host meodel/nest-app:latest 